version: "3"

services:
  api:
    image: "jamyth0712/eatwhatgood-backend"
    expose: 3001
  web:
    environment:
      VIRTUAL_HOST: eatwhatgood.jamyth.com
    image: "jamyth0712/eatwhatgood-frontend"
    expose:
      - 80
networks:
  default:
    external: true
    name: env-proxy
